views/partials/nav.ejs

Het toevoegen van de NAV (basic versie) aan het project

Toevoegen Jolan NAV versie test

---

public/styles/style.css
views/blacklist.ejs

Same principle as with blacklist. Media queries in css. Media queries & css in general needs to be cleaned up for both blacklist & favorites (i've worked mobile-first for favorites but desktop-first for blacklist, so that isn't proper), but I'll try to do that in a separate branch.

blacklist created

---

index.ts
package-lock.json
package.json
views/register.ejs

Created a register page using (tried) semantic HTML as requested.

Register page

---

public/styles/styleLandingPage.css
views/index.ejs
views/partials/headerMain.ejs

- created a new css file for landing page (can also be used for login and register page)
- updated the landing page (no sticky top, each card is now equal in height, intro text ...)

Header index

---

public/styles/style.css
views/blacklist.ejs
views/favorites.ejs

It seems like I changed a lot but technically I only changed some classes and cleaned up the media queries 😅 Maybe git didn't recognize that. Re the Character page, if you use the same class name as I did (.table-custom) with article for each entry, then it should automatically create the zebra pattern as well, for example

clean up html and css

---

views/index.ejs

centered titles, fixed links to img, bigger font intro text

Small updates to the landing page

---

public/styles/style.css
views/blacklist.ejs

Changed the edit-form into a bootstrap collapse component, so it appears as soon as you click the little edit button and also closes again.

Blacklist collapse

---

public/styles/style-quiz.css

Fix for modal-background + added background-color as safeguard before background-image in body

Modal background

---

index.ts
views/question.ejs
views/quiz.ejs

- created global activeUser variable for test functionality
- function to generateQuestions (quotes are unique + don't appear in blacklist)
- global questions variable is now filled by generateQuestions
- moved this functionality to a /quiz/ POST route so questions are generated when selecting a quiz to start
- left the order of the LOTR movies hardcoded because the options are normally always the same & chronological order is probably nicer for the user experience
- answer validation is done by default html
- functions to add answers to question array
- redirecting to next question by default, redirecting to score if quiz has ended
edit
- edited routes to make sure this doesn't merge with old routes still implemented

Question functionality

---

.env.example
db.ts
index.ts
views/login.ejs
views/register.ejs

Changed form to post in register.ejs,
Added createUser and getUser func in db.ts.
Implemented /register GET and POST routes.

Implemented register logic

---

.env.example
index.ts
views/character.ejs
views/favorites.ejs
views/index.ejs
views/partials/header-quiz.ejs
views/score.ejs

aanpassen zodat de links (opnieuw) werken

User user id remove

---

index.ts

This seems like a lot of new data, but I just moved the functions outside of the routes & optimized them slightly - git obviously could not keep track of this random copying & pasting, and registers a lot of it as new code.
The biggest change is just that questions are now added as needed, not in bulk. I changed the name from "generateQuestions" to "addNextQuestion" for this purpose. A question is created right before a quiz starts (in POST /quiz/), and questions will be added as default after every POST /question/. This is more efficient, as there will never be too many questions for a given quiz.
Aside from that I had to fix the error handling in the functions, since they were moved outside of the routes & res.status would not work anymore, so I added this via try/catch within the …

questions are now added as needed, not in bulk

---

index.ts

final touch

---

index.ts
public/scripts/alerts.js
public/styles/style.css
views/index.ejs
views/login.ejs
views/partials/header.ejs
views/register.ejs

created a script for creating alerts in 
register page: if the same username allready exists
login page: if the credentials don't exists in DB
and landing page: if you click on other projects than LOTR and ifyou click on LOTR project while not logged in yet

Alerts forr register, login and landing page

---

index.ts
public/scripts/alerts.js
views/index.ejs

added alert if psw and confirm psw are not identical
fixed spelling in alerts.js
deleted comment in index.ejs

Improved alert for register

---

db.ts
index.ts
public/scripts/thumbs.js
views/question.ejs

- added addToFavorites(user, favorite) func to db.ts & index.ts (POST req "/quiz/:type/question/:questionId")
- added addToBlacklist(user, blacklist) func to db.ts & index.ts (POST req "/quiz/:type/question/:questionId")
- made textarea “required” via thumbs.js (updated version)
- added text to thumbs-up & -down btns in question.ejs
- added “(verplicht)” after “Reden voor blacklisting?” text in question.ejs

Thumbs logic & other minor changes 

---

db.ts
index.ts
public/scripts/thumbs.js
views/character.ejs
views/question.ejs

- added additional func in db.ts:
- getUserFavorites()
- deleteFavorite()
- getUserBlacklist()
-  implemented app.get("/favorites/:characterId")
- implemented app.post("/favorites/:characterId/:quoteId/delete")

Implementation character GET & POST routes

---

db.ts
functions.ts
index.ts

- added 2 new functions to db.ts for writing answers to db and implemented in functions.ts

Writing questions and answers to db

---

db.ts
functions.ts
index.ts
views/score.ejs

- finalized refactoring the question-logic functions for the change to database system
- made small changes to the score logic to fix the functionality after refactoring

final refactoring for question functions & score functionality

---

db.ts
index.ts
views/question.ejs
views/register.ejs

- getUserByEmail func  in db.ts
- implemented the email check  in POST/register
- changed two error messages in POST/register
- added * to required fields in register and question ejs

Implementation getUserByEmail  func + error handling + '*' to required fields in ejs

---

index.ts
views/question.ejs

added logic for thumbs up and thumbs down

Thumbs up down logic

---

index.ts
views/blacklist.ejs
views/character.ejs
views/favorites.ejs
views/index.ejs
views/partials/header-quiz.ejs
views/question.ejs
views/quiz.ejs
views/score.ejs

- routes updated with /lotr/ prefix
- character routes updated with /character/ prefix

routes updated with /lotr/ prefix

---

index.ts
public/styles/style-quiz.css
views/favorites.ejs
views/question.ejs

Tried to change the outline of the a tags, but the one for the logo image doesn't work.
Also changed the button on the last question of the tenrounds quiz, but I couldn't test if it works because I can't access quiz.

Optional finetuning

---

public/scripts/preventLeaving.js
views/question.ejs

Added javascript script to warn the user before leaving the quiz question page, except when the user clicks the submit button. To this end, the header for quiz was added back into the question.ejs page, because the script needed to be adedd only for this page.

Question page alert
